### ISSUE TITLE
Customer service - style 12096837 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#358] opened 2015-07-26 13:44 UTC
Hi Lucas, 

Please check this style 12096837. 

We do not see any sizes or cannot select them.

Thank you in advance.

**Comment by jj-lucas** [comment] 2015-07-27 06:36
Closing, duplicate of jackjonesfashion/wiz#357

**Closed by jj-lucas** 2015-07-27 06:36 UTC
